module.exports = `/** ------ Generated by Ignite ------ */
/**
 * @name PKG_NAME
 * @version PKG_VERSION
 * @author PKG_AUTHOR
 * @description PKG_DESCRIPTION
 */
 module.exports = {
     name: "PKG_NAME",
     version: "PKG_VERSION",
     author: "PKG_AUTHOR",
     description: "PKG_DESCRIPTION",
     dependencies: [PKG_DEPENDENCIES],
     git: "PKG_GITREPO",
     scripts: {
         "test": "exit 0",
         "start": "node PKG_START"
     },
     config: {
         use_docker: PKG_USE_DOCKER,
         create_dockerfile: PKG_CREATE_DOCKERFILE,
         dockerfile: PKG_DOCKERFILE_BLOB
     }
 }
`;